### ISSUE TITLE
Configuration error of parameter "rows" in layout

### ISSUE THREAD

**Issue by Arachnos** [richardhj/contao-theme-framework#4]
When writing this in the configuration for layouts : 
```
layouts:
  _default:
    name: Default layout
    template: fe_page
    rows: 3rw
```
we got the following error : 
```
In ExceptionConverter.php line 88:

  An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the
  manual that corresponds to your MariaDB server version for the right syntax to use near 'rows = '3rw', alias = '_default', pid = '3', tstamp = '1651845
  701' WHERE id =...' at line 1

In Exception.php line 30:

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server
  version for the right syntax to use near 'rows = '3rw', alias = '_default', pid = '3', tstamp = '1651845701' WHERE id =...' at line 1

In Statement.php line 101:

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server
  version for the right syntax to use near 'rows = '3rw', alias = '_default', pid = '3', tstamp = '1651845701' WHERE id =...' at line 1
```

The parameter `rows` seems to be reserved in MariaDB, so we have to write the config this way, with backquotes, to make it work : 
```
layouts:
  _default:
    name: Default layout
    template: fe_page
    '`rows`': 3rw
```
